@setlocal

pushd %1

%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Actors.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Animations.json 1 2 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Armors.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Classes.json 1 2 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\CommonEvents.json 1 2 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Enemies.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Items.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\MapInfos.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Skills.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\States.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\System.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Tilesets.json 1 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Troops.json 1 2 3 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Weapons.json 

%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map001.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map002.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map003.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map004.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map005.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map006.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map007.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map008.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map009.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map010.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map011.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map012.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map013.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map014.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map015.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map016.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map017.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map018.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map019.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map020.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map021.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map022.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map023.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map024.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map025.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map026.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map027.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map028.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map029.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map030.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map031.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map032.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map033.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map034.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map035.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map036.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map037.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map038.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map039.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map040.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map041.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map042.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map043.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map044.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map045.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map046.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map047.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map048.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map049.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map050.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map051.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map052.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map053.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map054.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map055.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map056.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map057.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map058.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map059.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map060.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map061.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map062.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map063.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map064.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map065.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map066.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map067.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map068.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map069.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map070.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map071.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map072.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map073.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map074.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map075.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map076.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map077.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map078.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map079.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map080.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map081.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map082.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map083.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map084.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map085.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map086.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map087.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map088.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map089.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map090.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map091.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map092.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map093.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map094.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map095.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map096.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map097.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map098.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map099.json 
%~fd0\..\jsonNewlineByArr.cpp.exe docs\data\Map100.json 

